### ISSUE TITLE
Enabling the GUI for opencore

### ISSUE THREAD

**Issue by beta4better** [cmalf/HP-EliteDesk-800-G4-G5-Hackintosh#2]
Hi there, 
I want to enable the GUI for opencore, and followed the guide here:
https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html

But it not works, I also tried to reset the NVRAM. 
May you please check is there any other settings regarding this?

**Comment by cmalf** [comment]
I understand that guides aren't always entirely accurate.<br> Given my busy schedule right now, I'll provide a more concise solution.<br> Hopefully, this can help you resolve the 'OpenCore GUI' issue.<br> I've attached an EFI configuration that uses the 'bigsurflat' theme and 'scanpolicy 257', which is suitable for macOS. <br>If you're dual-booting, please change the 'scanpolicy' to 0. <br>For more flexible options, you can visit my repository at [oc-scanpolicy-generator](https://github.com/cmalf/oc-scanpolicy-generator). <br>Essentially, to set up the GUI in OC, you'll need OpenCanopy and ensure that the MISC and UEFI settings are synchronized. <br>
[EFI.zip](https://github.com/user-attachments/files/17994461/EFI.zip)

**Comment by beta4better** [comment]
> I understand that guides aren't always entirely accurate. Given my busy schedule right now, I'll provide a more concise solution. Hopefully, this can help you resolve the 'OpenCore GUI' issue. I've attached an EFI configuration that uses the 'bigsurflat' theme and 'scanpolicy 257', which is suitable for macOS. If you're dual-booting, please change the 'scanpolicy' to 0. For more flexible options, you can visit my repository at [oc-scanpolicy-generator](https://github.com/cmalf/oc-scanpolicy-generator). Essentially, to set up the GUI in OC, you'll need OpenCanopy and ensure that the MISC and UEFI settings are synchronized. [EFI.zip](https://github.com/user-attachments/files/17994667/EFI.zip)

Verified, it works, thanks so much.
Really nice theme.
